### ISSUE TITLE
Dragonflight implementation checklist

### ISSUE THREAD

**Issue by Niphyr** [MechanicalPriest/Salvation#161]
### Base Spells (Priest)
- [ ] Desperate Prayer
- [ ] Fade
- [ ] Flash Heal
- [ ] Levitate
- [ ] Mind Soothe
- [ ] Mind Vision
- [ ] Power Word: Fortitude
- [ ] Power Word: Shield
- [ ] Prayer of Mending
- [ ] Psychic Scream
- [ ] Renew
- [ ] Resurrection
- [ ] Shadow Word: Pain
- [ ] Smite
- [ ] Focused Will

### Base Spells (Holy)
- [ ] Heal
- [ ] Holy Fire
- [ ] Mass Resurrection
- [ ] Purify
- [ ] Mastery: Echo of Light
- [ ] Spirit of Redemption

**Comment by Niphyr** [comment]
Implementation of Echo of Light requires tests to validate spells that do/don't trigger mastery.

**Comment by Niphyr** [comment]
> Implementation of Echo of Light requires tests to validate spells that do/don't trigger mastery.

Done in `SpellServiceDests.cs`

**Comment by Niphyr** [comment]
Full list of spells that aren't planned to be implemented below.

### Base Spells (Priest)
- Levitate
- Mind Soothe
- Mind Vision
- Power Word: Fortitude
- Psychic Scream
- Resurrection
- Focused Will

### Base Spells (Holy)
- Mass Resurrection

### Talents (Priest)
- Dispel Magic
- Improved Purify
- Psychic Voice
- Angelic Feather
- Phantasm
- Blessed Recovery
- Leap of Faith
- Shackle Undead
- Sheer Terror
- Void Tendrils
- Mind Control
- Dominate Mind
- Move with Grace
- Vampiric Embrace
- Body and Soul
- Void Shield
- San'layn
- Apathy
- Crystalline Reflection
- Void Shift

### Talents (Holy)
- Censure

**Comment by Niphyr** [comment]
## Low Priority Implementations
### Base Spells (Priest)
- [ ] Desperate Prayer
